soporte/config/routes.rb
Rails.application.routes.draw do
resources :estados

end

soporte/app/models/estado.rb
class Estado < ActiveRecord::Base
end

soporte/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

soporte/app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :get_Estado,only: [:update,:show,:destroy,:edit]
  def index
    @estados = Estado.all
  end

  def new
    @estado = Estado.new
  end
  def edit
  end

  def create
    @estado = Estado.new(estados_params)
    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'el estado fue creado con exito' }
        format.json { render :show, status: :created, location: @estado }
      end
    end
  end

  def show
  end
  def update
    respond_to do |format|
      if @estado.update(estados_params)
        format.html{redirect_to @estado,notice: 'estado editado'}
        format.json{redirect_to @estado}
      end
    end
  end

  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_path, notice: 'Estado Eliminado' }
      format.json { head :no_content }
    end
  end

  private
  def get_Estado
    @estado = Estado.find(params[:id])
  end
  def estados_params
    params.require(:estado).permit(:id,:descripcion)
  end
end

soporte/app/helpers/application_helper.rb
module ApplicationHelper
end

soporte/app/helpers/estados_helper.rb
module EstadosHelper
end

soporte/app/views/estados/_form.html.erb
<%= form_for(@estado) do |f| %>
  <% if @estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
      <% @estado.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <%end %>
  <div class="field">
    <%= f.label :descripcion %>
    <%= f.text_field :descripcion %>
  </div>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

soporte/app/views/estados/edit.html.erb
<%= render 'form' %>

soporte/app/views/estados/index.html.erb
<h1>Listado de Estados</h1>
<%= link_to 'Nuevo Estado',new_estado_path %>
<table  border='1'>	
	<tr>
		<th>Id</th>
		<th>Descripcion</th>
		<th>acciones</th>
	</tr>
	<% @estados.each do |estado| %>
	<tr>
		<td><%= estado.id %></td>	
		<td><%= estado.descripcion%></td>
		<td>
			<%= link_to 'Editar',edit_estado_path(estado) %>||
		<%= link_to 'Eliminar', estado, method: :delete, data: { confirm: 'Are you sure?' } %>
		</td>	
	</tr>
	<% end %>

soporte/app/views/estados/new.html.erb
<%=  form_for @estado  do |f| %>
	<%= f.label :descripcion %>
	<%= f.text_field :descripcion %>
	<%= f.submit 'Crear Estado' %>
<%end %>

soporte/app/views/estados/show.html.erb
<p><%= notice %></p>
<h1>Estado</h1>
<table  border='1'>	
	<tr>
		<th>Id</th>
		<th>Descripcion</th>
		<th>acciones</th>
	</tr>
	<tr>
		<td><%= @estado.id %></td>	
		<td><%= @estado.descripcion%></td>
		<td>
			<%= link_to 'Editar',edit_estado_path(@estado) %>||
		<%= link_to 'Eliminar', @estado, method: :delete, data: { confirm: 'Are you sure?' } %>
		</td>	
	</tr>
</table>

soporte/app/views/estados/update.html.erb
<h1>Estados#update</h1>
<p>Find me in app/views/estados/update.html.erb</p>

soporte/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soporte</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>